name: ${project.name}
main: com.poixson.repeater2way.Repeater2WayPlugin
version: ${project.version}
api-version: ${spigot-short-version}
depend:
  - pxnCommonPluginMC
authors: [ lorenzop ]
website: ${project.url}
description: ${project.description}
