name: ${project.name}
main: com.poixson.repeater2way.Repeater2WayPlugin
version: ${project.version}
api-version: ${spigot-short-version}
depend: [ pxnCommonBukkit ]
authors: [ lorenzop ]
website: ${project.url}
description: ${project.description}
permission-message: "You don't have permission to use this command."
